---
- name: Check if git is installed
  command: which git
  register: git_check
  failed_when: false
  changed_when: false
  tags:
    - git
    - check

- name: Display git status
  debug:
    msg: "Git is {{ 'already installed' if git_check.rc == 0 else 'not installed' }}"
  tags:
    - git

- name: Install git if not present
  apt:
    name: git
    state: present
    update_cache: yes
  when: git_check.rc != 0
  tags:
    - git
    - install

- name: Verify git installation
  command: git --version
  register: git_version
  changed_when: false
  tags:
    - git
    - verify

- name: Display git version
  debug:
    msg: "Git version: {{ git_version.stdout }}"
  tags:
    - git

- name: Configure git global settings (optional)
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: "init.defaultBranch", value: "main" }
    - { name: "pull.rebase", value: "false" }
    - { name: "core.autocrlf", value: "input" }
  become: no
  become_user: "{{ ansible_user_id }}"
  ignore_errors: yes
  tags:
    - git
    - config