---
- name: Download Obsidian AppImage
  get_url:
    url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.4.16/Obsidian-1.4.16.AppImage"
    dest: "/opt/Obsidian.AppImage"
    mode: '0755'
  become: true
  become_method: sudo

- name: Create Obsidian desktop entry
  copy:
    content: |
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=Obsidian
      Comment=A powerful knowledge base that works on top of a local folder of plain text Markdown files
      Exec=/opt/Obsidian.AppImage
      Icon=obsidian
      Terminal=false
      Categories=Office;
    dest: /usr/share/applications/obsidian.desktop
    mode: '0644'
  become: true