---
- name: Check if Visual Studio Code is already installed
  command: which code
  register: vscode_check
  failed_when: false
  changed_when: false
  tags:
    - vscode
    - check

- name: Display VSCode status
  debug:
    msg: "Visual Studio Code is {{ 'already installed' if vscode_check.rc == 0 else 'not installed' }}"
  tags:
    - vscode

- name: Install dependencies for VSCode
  apt:
    name:
      - wget
      - gpg
      - apt-transport-https
    state: present
  when: vscode_check.rc != 0
  tags:
    - vscode
    - dependencies
  become: true
  become_method: sudo

- name: Download Microsoft GPG key
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc
    mode: "0644"
  when: vscode_check.rc != 0
  tags:
    - vscode
    - gpg
  become: true
  become_method: sudo

- name: Add Microsoft GPG key
  shell: |
    gpg --dearmor < /tmp/microsoft.asc > /tmp/packages.microsoft.gpg
    install -o root -g root -m 644 /tmp/packages.microsoft.gpg /etc/apt/trusted.gpg.d/
  when: vscode_check.rc != 0
  tags:
    - vscode
    - gpg
  become: true
  become_method: sudo

- name: Add Visual Studio Code repository
  apt_repository:
    repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    state: present
    filename: vscode
  when: vscode_check.rc != 0
  tags:
    - vscode
    - repository
  become: true
  become_method: sudo

- name: Update package cache after adding VSCode repository
  apt:
    update_cache: yes
  when: vscode_check.rc != 0
  tags:
    - vscode
    - update
  become: true
  become_method: sudo

- name: Install Visual Studio Code
  apt:
    name: code
    state: present
  when: vscode_check.rc != 0
  tags:
    - vscode
    - install
  become: true