---
cache_valid_time: 3600
upgrade_type: dist

# Packages to install
packages:
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - software-properties-common
  - gobuster
  - zaproxy
  - ncat
  - build-essential
  - golang-go
  - python3
  - python3-pip
  - pipx
  - curl
  - wget
  - unzip
  - vim
  - htop
  - tree
  - firefox-esr

# Aliases
zsh_aliases:
  - "alias ll='ls -alF'"
  - "alias la='ls -A'"
  - "alias l='ls -CF'"
  - "alias linpeas='/opt/peass-ng/linpeas.sh'"
  - "alias seclists='cd /opt/SecLists'"
  - "alias peass='cd /opt/peass-ng'"

# Define fonts to install
fonts:
  # MesloLGS NF
  - url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.fonts/meslolgs_nf_regular.ttf"
    mode: "0755"
  - url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.fonts/meslolgs_nf_bold.ttf"
    mode: "0755"
  - url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.fonts/meslolgs_nf_italic.ttf"
    mode: "0755"
  - url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.fonts/meslolgs_nf_bold_italic.ttf"
    mode: "0755"
