---
# Burp Suite Certificate
- name: "Check if BurpSuiteCA.der exists"
  stat:
    path: /usr/local/share/ca-certificates/BurpSuiteCA.der
  register: burp_cert
  
- name: "Copying Burp Script"
  copy:
    src: files/getburpcert.sh
    dest: /tmp/getburpcert.sh
    mode: 0755
  when: burp_cert.stat.exists == False
  become: no

- name: "Executing bash script to Download CA Certificate"
  shell:
    /tmp/getburpcert.sh
  when: burp_cert.stat.exists == False
  become: no

- name: "Copying CA Certificate to /usr/local/share/ca-certificates"
  copy:
    src: /tmp/cacert.der
    dest: /usr/local/share/ca-certificates/BurpSuiteCA.der
    owner: root
    group: root
    mode: 0644
  become: true
  become_method: sudo
  when: burp_cert.stat.exists == False

- name: Create directory for Burp Suite extras
  ansible.builtin.file:
    path: "{{ burpsuite_extras_dir }}"
    state: directory
    mode: '0755'
  become: true
  become_method: sudo

- name: Download jar files
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ burpsuite_extras_dir }}/{{ item.value.jar }}"
    checksum: "{{ item.value.checksum }}"
    mode: '0644'
  become: true
  become_method: sudo
  loop: "{{ lookup('dict', burpsuite_extras_jars) }}"
  
- name: Copy BurpSuite Community Config
  template:
    src: "templates/ConfigCommunity.json.j2"
    dest: "{{ ansible_env.HOME }}/.BurpSuite/ConfigCommunity.json"
  become: no

- name: Ensure Firefox ESR distribution directory exists
  ansible.builtin.file:
    path: "/usr/share/firefox-esr/distribution"
    state: directory
    mode: '0755'
  become: true
  become_method: sudo
  
- name: "Updating Firefox Policies"
  template: 
    src: "templates/policy.json.j2"
    dest: "/usr/share/firefox-esr/distribution/policies.json"
  become: true
  become_method: sudo
