---
- name: Remove useless packages from cache
  apt:
    autoclean: true 
  become: true
  become_method: sudo

- name: Restart QTerminal processes (if running)
  shell: |
    pkill -f qterminal || true
  ignore_errors: yes
  become: yes
  become_user: kali
