---
# Configuration for sudoers
- name: Add NOPASSWD rule for the current user
  become: true
  lineinfile:
    dest: /etc/sudoers
    insertbefore: EOF
    regexp: "{{ ansible_user_id }} ALL="
    line: "{{ item }}"
    validate: visudo -cf %s
  when: ansible_user_id != 'root'
  with_items:
    - "{{ ansible_user_id }}\tALL=(ALL) NOPASSWD:ALL"

# Configuration for terminal transparency
- name: Check if qterminal_bookmarks.xml exists
  stat:
    path: "{{ ansible_env.HOME }}/.config/qterminal.org/qterminal_bookmarks.xml"
  register: qterminal_bookmarks_file


- name: Set QTerminal transparency
  ansible.builtin.template:
    src: templates/qterminal.ini.j2
    dest: "{{ ansible_env.HOME }}/.config/qterminal.org/qterminal.ini"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
  when: not qterminal_bookmarks_file.stat.exists
