# Configuration for tmux
- name: Ensure Tmux is installed.
  ansible.builtin.apt:
    name: "tmux"
    state: present
  become: true
  become_method: sudo

- name: Set .tmux.conf settings
  ansible.builtin.template:
    src: templates/tmux.conf.j2
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Ensure .tmux directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.tmux/"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory

- name: Ensure tmux plugins directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.tmux/plugins/"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory

- name: Install TPM to handle tmux tmux-plugins
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

- name: Check if TPM plugin (e.g. tmux-sensible) is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.tmux/plugins/tmux-sensible"
  register: tmux_plugin_installed

- name: Run Tmux TPM post install script
  ansible.builtin.shell: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins"
  args:
    executable: /bin/zsh
  when: not tmux_plugin_installed.stat.exists
