---
# Configuration for aliases
- name: Add useful aliases to zshrc
  become: no
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  loop: "{{ zsh_aliases }}"

# Configuration for pipx
- name: Ensure pipx is properly configured for user
  become: no
  shell: |
    pipx ensurepath
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> {{ ansible_env.HOME }}/.zshrc
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin"

- name: Source zshrc to update PATH
  become: no
  shell: source {{ ansible_env.HOME }}/.zshrc
  args:
    executable: /bin/zsh

# Configuration for sudoers
- name: Add NOPASSWD rule for the current user
  become: true
  lineinfile:
    dest: /etc/sudoers
    insertbefore: EOF
    regexp: "{{ ansible_user_id }} ALL="
    line: "{{ item }}"
    validate: visudo -cf %s
  when: ansible_user_id != 'root'
  with_items:
    - "{{ ansible_user_id }}\tALL=(ALL) NOPASSWD:ALL"

# Configuration for terminal transparency
- name: Create qterminal_bookmarks.xml file
  file:
    path: "{{ ansible_env.HOME }}/.config/qterminal.org/qterminal_bookmarks.xml"
    state: touch
    owner: kali
    group: kali
    mode: '0644'

- name: Set QTerminal transparency
  ansible.builtin.template:
    src: templates/qterminal.ini.j2
    dest: "{{ ansible_env.HOME }}/.config/qterminal.org/qterminal.ini"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644