---
- name: Update and Install packages
  import_tasks: config-packages.yml

# - name: Configuration for terminal
#   import_tasks: config-terminal.yml

- name: Configuration for tmux
  import_tasks: config-tmux.yml

- name: Installation of powerlevel10k
  import_tasks: config-powerlevel.yml
  